### ISSUE TITLE
Enhancement: Add key listing feature

### ISSUE THREAD

**Issue by rgordill** [infinispan/infinispan-console#112]
As a developer using infinispan and the console, it will be very useful for debugging purposes if I can see a list of keys inserted (probably with a limit) so I can click on a single record and see the value.

I assume the REST API https://infinispan.org/docs/dev/titles/rest/rest.html#rest_v2_get_keys, can be used for that.

Thanks!

**Comment by karesti** [comment]
already coming in 12!
