### ISSUE TITLE
Console - fields mixed in chart's legend

### ISSUE THREAD

**Issue by 50qbits** [infinispan/infinispan-console#123]
![Screenshot_2021-02-11 Cache](https://user-images.githubusercontent.com/45095136/107693150-08a3e480-6cae-11eb-9a55-e62215a35382.png)

Server Management console > Data container > Detail of cache > Data access chart
Retrievals and stores fields are mixed in pie chart.

Enhancement: aggregated units in pie chart (K,M,B)

**Comment by karesti** [comment]
https://issues.redhat.com/browse/ISPN-12749
