### ISSUE TITLE
Read isolation levels in the cache builder (wizard)

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-console#203]
There should only be two options for the read isolation level when creating a cache via the wizard: REPEATABLE_READ (default) and READ_COMMITTED.

SERIALIZABLE and READ_UNCOMMITTED are not supported. NONE is for local caches only.

**Comment by dipguptaredhat** [comment]
@oraNod Isolation level options are already corrected, can close this issue?

**Comment by oraNod** [comment]
@dipguptaredhat Yes! Please close if this is fixed. I added just to be sure it wasn't missed.
