### ISSUE TITLE
Asterisk on cache wizard name field

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan-console#221]
Asterisk indicates a required field but there is no call out or corresponding explanation. Looks like the asterisk is just dangling there. 

We should either remove it or add a tooltip saying "You must provide a unique name for your cache."

![image](https://user-images.githubusercontent.com/32749632/173799205-c4597c0b-59e3-429e-a550-2d507d86850b.png)

**Comment by karesti** [comment]
This is done on the refactoring
