### ISSUE TITLE
Upgrade react-router-dom

### ISSUE THREAD

**Issue by dpanshug** [infinispan/infinispan-console#393]
### Description

Update the `react-router-dom` package to the latest version and ensure that all code changes required throughout the project are implemented accordingly.

JIRA: https://issues.redhat.com/browse/ISPN-15146

### Anything else?

Reference links: https://reactrouter.com/en/main/upgrading/v5#upgrading-from-v5

**Comment by Equinox-67** [comment]
Hi, I would love to take up this issue.

**Comment by dpanshug** [comment]
Issue assigned @Equinox-67 :heavy_check_mark:
