### ISSUE TITLE
[Feature Request]: Update Table component for XSiteCache

### ISSUE THREAD

**Issue by dpanshug** [infinispan/infinispan-console#399]
### Feature description

Update the Table component for XSiteCache from Patternfly 4 to 5.
https://github.com/infinispan/infinispan-console/blob/e5f6872ef18f009d522577c802332306516a51c6/src/app/XSite/XSiteCache.tsx#L28

https://github.com/infinispan/infinispan-console/blob/e5f6872ef18f009d522577c802332306516a51c6/src/app/XSite/XSiteCache.tsx#L351

JIRA: https://issues.redhat.com/browse/ISPN-14027

### Anything else?

Hint: See other updated Table components like [here](https://github.com/infinispan/infinispan-console/blob/e5f6872ef18f009d522577c802332306516a51c6/src/app/CacheManagers/CacheTableDisplay.tsx#L710).

Reference links: https://www.patternfly.org/components/table

**Comment by karesti** [comment]
done
