### ISSUE TITLE
Web Console does not allow to create caches with cross-site enabled

### ISSUE THREAD

**Issue by pruivo** [infinispan/infinispan-console#529]
### Describe the bug

When trying to add the `backups` feature, it says `Backups are disabled` although in the `Data Container` page it detects the site's name just fine. 

![xsite1](https://github.com/user-attachments/assets/c025d8b6-f550-408d-9f92-6013c2bca189)
![xsite2](https://github.com/user-attachments/assets/15080e42-8ec1-4516-90b3-b509a6bcfaca)

### Expected behavior

I'm expecting to be able to create caches with `backups` :)

### Actual behavior

I'm unable to create caches with `backups` :( 

### How to Reproduce?

1. Start a server: 
```
podman run -e USER=admin -e PASS=admin --network host quay.io/infinispan/server:15.0.10.Final -c infinispan-xsite.xml -b 127.0.0.1 -k 127.0.0.1
```
2. Access and login into the web console on http://127.0.0.1:11222
3. Click on `Create cache` and give it a name `test`. Click next
4. On the second page click next
5. On `Add Infinispan capabilities`, add `Backups` and I'm unable to proceed

### Output of `uname -a` or `ver`

Linux pedro-desktop 6.11.2-4-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct  8 11:52:01 UTC 2024 x86_64 GNU/Linux

### Infinispan version or git rev

15.0.10.Final

**Comment by karesti** [comment]
@pruivo I can't run the container with  -b 127.0.0.1 -k 127.0.0.1 

If I remove those, I run it and I can create backups

![Screenshot 2024-10-16 at 10 53 35](https://github.com/user-attachments/assets/1590198f-5889-4ae2-9047-5d57c8b6dbd2)

**Comment by karesti** [comment]
@pruivo sorry, I was running 15.1 not 15.0. There is a bug in 15.0

**Comment by pruivo** [comment]
Thanks @karesti !
